name: run monitor Ap

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: playwright install
      - run: python app.py
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update data"
          git push