name: run app.py

# on:
#   schedule:
#     - cron: '*/5 * * * *'

on:
    push:
        branches: [main]
    # pull_request:
    #     branches: [master]

jobs:
  run_schedule:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: playwright install
      - run: python src/app.py
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Add changes"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: check conteudo do repositorio
      #   uses: actions/checkout@v3

      # - name: instalar o python
      #   uses: actions/setup-python@v311

      # - name: instalar os pacotes do requirements.txt
      #   run: python -m pip install pip install -r requirements.txt

      # - name: executar arquivo principal
      #   run: python src/app.py